{% set version = "1.2.15" %}

package:
  name: brial-split
  version: {{ version }}

source:
  url: https://github.com/BRiAl/BRiAl/releases/download/{{ version }}/brial-{{ version }}.tar.bz2
  sha256: 1d0e7de01b1b60ad892dee6c02503f5932e2ed211f3f8dbdf1a3216c696ef201

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports_from:
    - libboost-devel

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
    - make

outputs:
  - name: libbrial
    script: build_libbrial.sh
    run_exports:
      # Releases of brial are very rare. 1.2.11 seems to have changed
      # inheritance structure, which might be a breaking ABI change so we pin
      # exactly.
      - {{ pin_subpackage("libbrial", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - libtool
        - pkg-config
        - make
        - gnuconfig
      host:
        - libpng
        - libboost-devel
        - m4ri
        - zlib
      run:
        - libpng
        - m4ri
        - zlib
    test:
      commands:
        - test -f ${PREFIX}/include/polybori.h
        - test -f ${PREFIX}/lib/libbrial.so     # [linux]
        - test -f ${PREFIX}/lib/libbrial.dylib  # [osx]

about:
  home: https://github.com/BRiAl/BRiAl
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Brial - successor to PolyBoRi
  description: |
    The core of PolyBoRi is a C++ library, which provides high-level data
    types for Boolean polynomials and monomials, exponent vectors, as well
    as for the underlying polynomial rings and subsets of the powerset of
    the Boolean variables. As a unique approach, binary decision diagrams
    are used as internal storage type for polynomial structures. On top of
    this C++-library we provide a Python interface. This allows parsing of
    complex polynomial systems, as well as sophisticated and extendable
    strategies for Gröbner base computation. PolyBoRi features a powerful
    reference implementation for Gröbner basis computation.
  dev_url: https://github.com/BRiAl/BRiAl

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
