{% set version = "1.2.2" %}
{% set name = "brial" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/BRiAl/BRiAl/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: 118c492c5f122f2e66dbff52fe9a660f7c4ff81da5afbed225967dded7d9a10e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - libtool
    - gmp >=5.0.1,<7
    - libpng >=1.6.28,<1.7
    - boost-cpp 1.66.*
    - python
    - pkgconfig
    - m4ri
  run:
    - gmp >=5.0.1,<7
    - libpng >=1.6.28,<1.7
    - boost-cpp 1.66.*
    - m4ri
    - python

test:
  commands:
    # Cannot run tests for python library as sageruntime is required.
    - test -f ${PREFIX}/include/polybori.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]

about:
  home: https://github.com/BRiAl/BRiAl
  license: GPLv2+
  license_file: {{ SRC_DIR }}/LICENSE
  summary: Brial - successor to PolyBoRi
  description: |
    The core of PolyBoRi is a C++ library, which provides high-level data
    types for Boolean polynomials and monomials, exponent vectors, as well
    as for the underlying polynomial rings and subsets of the powerset of
    the Boolean variables. As a unique approach, binary decision diagrams
    are used as internal storage type for polynomial structures. On top of
    this C++-library we provide a Python interface. This allows parsing of
    complex polynomial systems, as well as sophisticated and extendable
    strategies for Gröbner base computation. PolyBoRi features a powerful
    reference implementation for Gröbner basis computation.
  dev_url: https://github.com/BRiAl/BRiAl

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
