{% set version = "1.2.4" %}
{% set name = "libbrial" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/BRiAl/BRiAl/releases/download/{{ version }}/brial-{{ version }}.tar.bz2
  sha256: 60406a669f3fc5f8ed28ac501a9abd53b1ffead6f3c1028f927eca57403664ba

build:
  number: 0
  skip: true  # [win]

test:
  commands:
    - test -f ${PREFIX}/include/polybori.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    # Cannot run tests for python library as sageruntime is required.
    - test -f $SP_DIR/brial/PyPolyBoRi.py

outputs:
  - name: libbrial
    script: build_libbrial.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - libtool
        - pkg-config
      host:
        - gmp
        - libpng
        - boost
        - m4ri
        - zlib
      run:
        - gmp
        - libpng
        - boost
        - m4ri
        - zlib

  - name: brial
    build:
      noarch: python
    script: build_brial.sh
    requirements:
      host:
        - python
        - pip
        - {{ pin_subpackage('libbrial', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('libbrial', exact=True) }}

about:
  home: https://github.com/BRiAl/BRiAl
  license: GPLv2+
  license_file: {{ SRC_DIR }}/LICENSE
  summary: Brial - successor to PolyBoRi
  description: |
    The core of PolyBoRi is a C++ library, which provides high-level data
    types for Boolean polynomials and monomials, exponent vectors, as well
    as for the underlying polynomial rings and subsets of the powerset of
    the Boolean variables. As a unique approach, binary decision diagrams
    are used as internal storage type for polynomial structures. On top of
    this C++-library we provide a Python interface. This allows parsing of
    complex polynomial systems, as well as sophisticated and extendable
    strategies for Gröbner base computation. PolyBoRi features a powerful
    reference implementation for Gröbner basis computation.
  dev_url: https://github.com/BRiAl/BRiAl

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
