travis:
  secure:
    BINSTAR_TOKEN: TR3qZAARdvjO9ffGJrBoX90oASPOD/XS97NoEFedQopd7HpGPikDRPAUHfRhDsvxXx1cpEFL3awzk7q2wQB/wI84iC2r2nrmwfWS/LT6r0JCCG0zOsYmiWXlgcVnh9wxsu+1LdUPYbwQoHktX6iDs4rU4dnRSD/rMdOb9QAo8zxq67wWCOZs/K21zGtbhBgxPm/RuZCKe0f/lNdemSgnCRCUClHFJ79jojSndZ6XcVV4isYPkb4Ro7I1DF4axSWmdle47Q7PiPb2OZGDDGwhjFm0h/ve/bH6hnxU+I4Vr3I+DSxt3eL9IHV5koj6VhUbhILunfiChexPAKv7NUgweEhOpdWJswViQtmDXtSomB2jEciJVADsQc7LHy11S8upKzwlhIrMA4b908IV/blW2GPO7H6t4a0kp8ncOl/SbECVkbjOysD9ak80LCYm5Xu8NGSJMuHHlcE3NDF9eR67GSKXW31/z7mWBrfzQSu4juaKZrxfInSCtMz1/Fd08HEap1t7DVp7GsDoCBTPoODeLT/RxrErNOEFXy1yBH1kyowzq2eLlJx7iZ4ZrvsOdmNplBUG09bVbv1Z6Os0VxKyfd5rzj2rfOrWOHHNCQp/RYVoPYaIdhW1nph8MMlBf6/dmQzxKcW2PYs5mQPth1y38kaDFwG6b+RzOLgf800BbiU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
