travis:
  secure:
    BINSTAR_TOKEN: r9sj70hZi1NC/Ffxm/Km5+boIxx9kRNvRFX5I8P3HU3C8SK9RftPIc3wupIyjYz1YBrDlp43QnHGHv86BVF6pY8IhbfmQZQyt8CVd07+KLJCOYoTHmILQR0RbRkfo8tXsa4Dfc2QSteDdCHUbZ9PBlzo+C5KzS6Qn+vRlWQZkI1qVpENANyuEvDzymuYEdZ6pWZHxnM9SYKKOKqrxoRi8b1zf69AleG3zLAeGohQ4/eHsfVymWjajMN1fepp5c2pcXJcAXmISm0yVD+raSbnnWy+cAZZRhMGBMlvgu1CW+dWJBg6+hIV7hUeXOzHb9SuL1TrqF6xtX8PnzOyVuknshqdLGzvKi6VUsCueZQWPJdrlcuZjeLSS0P1E859H9ftjEV8GWs0LREP2A82G6Cavow/1KXKud+V02bTJo7wM6AZurzouQbh+FWevYpRsd/VCgeDKleapsN1LxHPgGJfcx+Um+dsNs4kAcunyVfpsIt3OrjSggXK336kVjLO5ewT0xpJM3lNrfy6TmeDkQqCCNKLC2/9Ydag9WyGCDXu51PPSH3ff9/mEWpGNEvbnbsvWKptamDegxCqN6kMDHhT4lHpbAgrKv9RZB0vKQF+QyW7Rm5j0CFNrNiCt6HO4vxHQG4O1tON+EuEtOdQ5BWYFi3e/zfYB1wFeZgy2EgZI6g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
